# Generated by Django 4.1.5 on 2023-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
