# Generated by Django 4.1.5 on 2023-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0002_alter_attraction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
