# Generated by Django 4.1.5 on 2023-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0003_alter_attraction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='day',
            field=models.DateField(),
        ),
    ]
