# Generated by Django 4.1.5 on 2023-01-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0004_alter_attraction_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attraction',
            new_name='Attractions',
        ),
    ]
