# Generated by Django 4.1.5 on 2023-01-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0005_rename_attraction_attractions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayClss',
        ),
    ]
