# Generated by Django 4.1.5 on 2023-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0006_delete_dayclss'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='image',
            field=models.ImageField(default='', upload_to='GuestService'),
        ),
    ]
