# Generated by Django 4.1.5 on 2023-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0007_attractions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='day',
            field=models.DateField(default=''),
        ),
    ]
