# Generated by Django 4.1.5 on 2023-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0009_alter_attractions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='image',
            field=models.ImageField(default='', upload_to='GuestService/static'),
        ),
    ]
