# Generated by Django 4.1.5 on 2023-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0010_alter_attractions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='image_of_us',
            field=models.ImageField(default='', upload_to='GuestService/static'),
        ),
    ]
