# Generated by Django 4.1.5 on 2023-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0011_attractions_image_of_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='experience',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
