# Generated by Django 4.1.5 on 2023-01-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0013_alter_attractions_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='image_of_us',
            field=models.ImageField(blank=True, default='', upload_to='GuestService/static'),
        ),
    ]
