# Generated by Django 4.1.5 on 2023-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0017_alter_attractions_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='day',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
