# Generated by Django 4.1.5 on 2023-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0018_alter_attractions_day_alter_attractions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
