# Generated by Django 4.1.5 on 2023-01-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0019_alter_attractions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='attractions',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestService.days'),
        ),
    ]
