# Generated by Django 4.1.5 on 2023-01-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0020_days_alter_attractions_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestService.attractions'),
        ),
    ]
