# Generated by Django 4.1.5 on 2023-01-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0021_alter_attractions_day_alter_days_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='stop_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestService.days'),
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('13. 2. 2023', 'Day 1'), ('14. 2. 2023', 'Day 2'), ('15. 2. 2023', 'Day 3'), ('16. 2. 2023', 'Day 4'), ('17. 2. 2023 ', 'Day 5'), ('18. 2. 2023', 'Day 6')], max_length=25, unique=True),
        ),
    ]
