# Generated by Django 4.1.5 on 2023-01-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0022_attractions_stop_number_alter_attractions_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('Day 1', '13. 2. 2023'), ('Day 2', '14. 2. 2023'), ('Day 3', '15. 2. 2023'), ('Day 4', '16. 2. 2023'), ('Day 5', '17. 2. 2023'), ('Day 6', '18. 2. 2023')], max_length=25, unique=True),
        ),
    ]
