# Generated by Django 4.1.5 on 2023-01-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuestService', '0023_alter_days_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='day',
            new_name='day_name',
        ),
    ]
